Podo-Store/BE

src/main/java/PodoeMarket/podoemarket/profile/controller/WorkController.java, src/main/java/PodoeMarket/podoemarket/profile/dto/WorkListResponseDTO.java, src/main/java/PodoeMarket/podoemarket/profile/service/WorkService.java
=> fix: 작품 관리 작가 이름 삭제 및 리팩토링(#202)

src/main/java/PodoeMarket/podoemarket/admin/controller/AdminController.java, src/main/java/PodoeMarket/podoemarket/admin/dto/request/UpdateTitleRequestDTO.java
=> feat: 어드민 작품 제목 변경(#265)

src/main/java/PodoeMarket/podoemarket/admin/controller/AdminController.java, src/main/java/PodoeMarket/podoemarket/admin/dto/request/UpdateWriterRequestDTO.java, src/main/java/PodoeMarket/podoemarket/admin/service/AdminService.java
=> feat: 어드민 작가명 변경(#268)

.github/workflows/deploy.yml
=> feat: deploy.yml slack webhook 추가

src/main/java/PodoeMarket/podoemarket/profile/controller/MypageController.java
close #291 
좋아요한 단편 작품 더보기 시, 매개변수 page가 사용되지 않고 0으로 고정되어 있었음
=> fix: 좋아요한 작품 단편 더보기(#291)

src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
close #295 
지속적인 커넥션 누수가 대본 미리보기에서 발생함을 로그에서 확인. 트랜잭션 처리가 필요한 부분과 불필요한 부분을 분리하고, 입력 스트림을 명시적으로 Close 및 예외 처리
=> bug: 대본 미리보기 커넥션 누수 수정(#295)

src/main/java/PodoeMarket/podoemarket/common/security/JwtAuthenticationFilter.java, src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
#295 -> 배포 로그 확인 후, close
Cross reference 오류 발생으로 안전모드 실행
=> fix: 미리보기 커넥션 누수 및 안전모드 설정(#295)

src/main/java/PodoeMarket/podoemarket/product/controller/ProductController.java, src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
#295 
데이터베이스 작업은 트랜잭션 내에서 수행. PDF 처리는 트랜잭션 외부에서 수행
=> fix: 커넥션 누수 처리(#295)

src/main/java/PodoeMarket/podoemarket/common/security/JwtAuthenticationFilter.java, src/main/java/PodoeMarket/podoemarket/product/controller/ProductController.java, src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
#295 
데이터베이스 작업은 트랜잭션 내에서 수행, PDF 처리는 트랜잭션 외부에서 수행. 또한, hikari 옵션 변경
=> fix: 미리보기 커넥션 누수 처리

src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
#308 서버 로그 확인 필요
ProductService에서 클랜스 전역적으로 적용되던 @Transactional(readOnly = true) 삭제, 메서드 별로 설정함
=> fix: 클래스 단의 트랜잭션 삭제(#308)

appspec.yml
#308 서버 로그 확인 필요
커넥션 누수 해결을 위한 코드 작성 후, 배포 로그 확인을 위함
=> fix: DB 커넥션 누수

src/main/java/PodoeMarket/podoemarket/product/controller/ProductController.java, src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java, src/main/java/PodoeMarket/podoemarket/profile/service/WorkService.java
=> feat: 대본 좋아요 여부 전달

src/main/java/PodoeMarket/podoemarket/order/dto/response/OrderItemResponseDTO.java, src/main/java/PodoeMarket/podoemarket/order/service/OrderService.java, src/main/java/PodoeMarket/podoemarket/profile/service/MypageService.java
=> fix: 자료형 변경에 따른 코드 수정(#341)

src/main/java/PodoeMarket/podoemarket/admin/service/AdminService.java, src/main/java/PodoeMarket/podoemarket/service/MailSendService.java
close #350 
작품 등록 후, 심사 결과 메일 전송
=> Feat: 작품 심사 결과 메일 전송

src/main/java/PodoeMarket/podoemarket/api/controller/ApiController.java, src/main/java/PodoeMarket/podoemarket/api/dto/response/SignInStatusResponseDTO.java, src/main/java/PodoeMarket/podoemarket/common/config/WebConfig.java
=> feat: 로그인 여부 확인 api 생성(#354)

src/main/java/PodoeMarket/podoemarket/user/service/UserService.java
close #356 
이메일 중복 시, 수정되었던 에러 메세지 재수정
=> fix: 이메일 중복 에러 메세지 수정(#356)

src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
close #363 
본인이 작성한 리뷰인지 확인하는 과정에서 로그인하지 않았을 경우 처리 없었음
=> fix: 로그인 안 할 경우 오류 수정(#363)

src/main/java/PodoeMarket/podoemarket/product/dto/response/ScriptDetailResponseDTO.java, src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
close #372 
리뷰 페이지네이션을 위한 전체 페이지 수 전달
=> fix: 페이지네이션을 위한 전체 페이지 수 전달(#372)

src/main/java/PodoeMarket/podoemarket/product/service/ProductService.java
close #375 
new URL(presignedURL).toURI.openStream() 하는 과정에서 URI 객체로 다시 변경하며 이미 인코딩된 문자열인 presignedURL을 다시 해석하여 오동작 발생
=> fix: 인코딩 문제 해결(#375)

src/main/java/PodoeMarket/podoemarket/profile/service/WorkService.java
제목, 줄거리, 작가의도에서 개행,이모지 문자 수를 1자로만 인식하도록 함
=> fix: 제목, 줄거리, 작가의도 개행,이모지 문자수 1자로만 인식처리

src/main/java/PodoeMarket/podoemarket/admin/service/AdminService.java
close #385 
어드민의 대본 다운로드 오류 해결
=> fix: zip 해제 코드 추가(#385)

src/main/java/PodoeMarket/podoemarket/common/config/WebConfig.java, src/main/java/PodoeMarket/podoemarket/profile/service/MypageService.java
=> [FIX] 닉네임 변경 시, 작가명 변경

.github/workflows/deploy.yml
=> fix: deploy.yml 수정(#401)

.github/workflows/deploy.yml, scripts/deploy.sh
=> fix: deploy.sh 수정(#401)

.github/workflows/deploy.yml, scripts/deploy.sh
=> [FIX] deploy.sh 수정

src/main/java/PodoeMarket/podoemarket/common/config/WebConfig.java
=> fix: 어드민 토큰 인증 에러

src/main/java/PodoeMarket/podoemarket/profile/service/MypageService.java
close #442 
주문한 작품들에 대한 삭제 여부 전달
=> fix: 주문한 작품 삭제 여부 전달(#442)

src/main/java/PodoeMarket/podoemarket/common/entity/OrderItemEntity.java, src/main/java/PodoeMarket/podoemarket/common/repository/UserRepository.java, src/main/java/PodoeMarket/podoemarket/order/service/OrderService.java, src/main/java/PodoeMarket/podoemarket/profile/service/MypageService.java
close #445 
주문 내역에서 삭제된 계정과 삭제된 작품이 제대로 분류되지 않음
=> fix: 주문 내역 - 삭제된 계정, 삭제된 작품 분리(#445)
